name: clean_news_ai
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:

  cloud_firestore:

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+1
  intl: ^0.15.7
  url_launcher: ^4.0.3
  share: ^0.5.3
  uuid: ^2.0.0
  shared_preferences: ^0.4.3
  tuple: ^1.0.2
  pull_to_refresh: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/load.png

